// import Head from "next/head";
import React from "react";
// import styles from "../styles/Home.module.css";
// import nextPackage from "package.json";

export default function Home({}) {
  return (
    // className={styles.container}
    <div>
      {/* <Head>
        <title>Next.js</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}
      {/* {nextPackage.version} */}
      Hello
    </div>
  );
}
